//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Drivers = new HashSet<Driver>();
            this.Outings = new HashSet<Outing>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual ICollection<Outing> Outings { get; set; }
    }
}
