//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.Outings = new HashSet<Outing>();
        }
    
        public int DriverId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Outing> Outings { get; set; }
    }
}
