//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerPreference
    {
        public int PassengerPreferenceId { get; set; }
        public Nullable<int> PassengerId { get; set; }
        public Nullable<int> PreferenceId { get; set; }
        public string Value { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Preference Preference { get; set; }
    }
}
