//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.PassengerPreferences = new HashSet<PassengerPreference>();
            this.StopPassengers = new HashSet<StopPassenger>();
        }
    
        public int PassengerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<decimal> CurrentLatitude { get; set; }
        public Nullable<decimal> CurrentLongitude { get; set; }
        public Nullable<int> CurrentOutingId { get; set; }
    
        public virtual ICollection<PassengerPreference> PassengerPreferences { get; set; }
        public virtual ICollection<StopPassenger> StopPassengers { get; set; }
        public virtual Outing CurrentOuting { get; set; }
    }
}
