//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public Preference()
        {
            this.PassengerPreferences = new HashSet<PassengerPreference>();
        }
    
        public int PreferenceId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PassengerPreference> PassengerPreferences { get; set; }
    }
}
