//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopPassenger
    {
        public int StopPassengerId { get; set; }
        public int StopId { get; set; }
        public int PassengerId { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Stop Stop { get; set; }
    }
}
