//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hackathon2.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopStatus
    {
        public StopStatus()
        {
            this.Stops = new HashSet<Stop>();
        }
    
        public short StopStatusId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Stop> Stops { get; set; }
    }
}
